name: welfare_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_email_sender: ^3.0.1
  intl: ^0.16.1
  shared_preferences: ^0.5.7+3
  sqflite: ^1.3.0+1
  path_provider: ^1.2.0
  path: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

